name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin]
    steps:
      - name: Checkout Passerine
        uses: actions/checkout@v2
        with:
          path: passerine

      - name: Checkout Aspen
        uses: actions/checkout@v2
        with:
          repository: vrtbl/aspen
          path: aspen

      - name: Compile and Release
        uses: Douile/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          SRC_DIR: aspen
